### ISSUE TITLE
This Module Working is Perfect . But I need to convert first page only ? Is it possible ? 

### ISSUE THREAD

**Issue by siamraj** [kb47/pdf-poppler#1]

**Comment by adrianbenjuya** [comment]
Hi, just set "1" in the "page" property under "opts"

`let opts = {
    format: 'jpeg',
    out_dir: path.dirname(file),
    out_prefix: path.baseName(file, path.extname(file)),
    page: 1
}`

**Comment by siamraj** [comment]
Yeah. I got it. Thanks
